#!/usr/bin/env bash
set -e # halt script on error

gem install jekyll
gem install 'github-pages'
echo "JEKYLL BUILD"
bundle exec jekyll build

echo ""
echo "HTML PROOFER"
bundle exec htmlproofer ./_site --disable-external
